### ISSUE TITLE
My app is complete, please review. /cc @codepathreview @codepath

### ISSUE THREAD

**Issue by anubharadwaj** [anubharadwaj/InstagramPhotoViewer#1]

**Comment by nesquena** [comment]
Hi Anu, you need to put the `@codepathreview @codepath` in the issue body and NOT the title in order for our submission tracker to pick it up. Can you make sure to do that for future submissions?

**Comment by nesquena** [comment]
It would be useful for you to add it to this issue as well so it will be picked up for the graders.

**Comment by anubharadwaj** [comment]
Hi Nathan,

Thanks for letting me know! I created a new issue with @codepath
@codepathreview in the description.

Cheers,
Anu
